---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "geerlingguy/docker-debian11-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
# platforms:
#   - name: instance
#     image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux8}-ansible:latest"
#     command: ${MOLECULE_DOCKER_COMMAND:-""}
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:rw
#     privileged: true
#     pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
